---
title: "CEA anticoag"
author: "Emily O'Neill, Andrew Huang"
date: "2023-06-06"
output: html_document
---

```{r} 
##remove any variables in R's Memory 
rm(list = ls()) 

##Install packages for Markov Model
library(here)
library(dplyr)

# Load function
source("function_plot-psa.R")

``` 

Read-in base case results for riv and war

```{r}

sim_results_war_noMC <- readRDS(here::here("output","results_1yr_war_noMC.rds"))
sim_results_riv_noMC <- readRDS(here::here("output","results_1yr_riv_noMC.rds"))

```

Calculate ICER from point estimates

```{r} 
###CEA 

##Store the estimated cost of each medication 
v.c <- c(sim_results_war_noMC$tc_hat, 
         sim_results_riv_noMC$tc_hat)
##store the estimated QALY of each medication  
v.e <- c(sim_results_war_noMC$te_hat, 
         sim_results_riv_noMC$te_hat)


## ICER ##
delta.c <- v.c[2] - v.c[1]            # calculate incremental costs between rivaroxaban and warfarin 
delta.e <- v.e[2] - v.e[1]            # calculate incremental QALYs between rivaroxaban and warfarin
ICER <- delta.c / delta.e             # calculate the ICER
results <- c(delta.c, delta.e, ICER)  # store the values in a new variable

# Create full incremental cost-effectiveness analysis table
table_markov <- data.frame(
  round(v.c, 0),              # costs per arm
  round(v.e, 4),              # health outcomes per arm
  c("", round(delta.c, 0)),   # incremental costs
  c("", round(delta.e, 4)),   # incremental QALYs
  c("", round(ICER, 0))       # ICER
)
rownames(table_markov) = c("Warfarin", "Rivaroxaban")  # name the rows
colnames(table_markov) = c("Costs", "QALYs","Incremental Costs", "QALYs Gained", "ICER") # name the columns
table_markov                    # print the table 
```

Read-in MC simulation results for riv and war

```{r}

sim_results_war <- readRDS(here::here("output","results_1yr_war.rds"))
sim_results_riv <- readRDS(here::here("output","results_1yr_riv.rds"))

sim_results_war <- sim_results_war %>%
  rename(tc_hatw = tc_hat) %>%
  rename(te_hatw = te_hat)

sim_results_riv <- sim_results_riv %>%
  rename(tc_hatr = tc_hat) %>%
  rename(te_hatr = te_hat)

```

Combine and compute ICERs

```{r}

sim_results <- inner_join(sim_results_war %>% select(nsim, tc_hatw, te_hatw),
                          sim_results_riv %>% select(nsim, tc_hatr, te_hatr),
                          by="nsim")

sim_results <- sim_results %>%
  mutate(delta.c = tc_hatr - tc_hatw,
         delta.e = te_hatr - te_hatw,
         icer = delta.c/delta.e)

summary(sim_results)

```

Distribution of ICER estimates

```{r}

# plot.psa(l_psa) +
#   ggthemes::scale_color_colorblind() +
#   ggthemes::scale_fill_colorblind() +
#   xlab("Effectiveness (QALYs)") +
#   guides(col = guide_legend(nrow = 2)) +
#   theme(legend.position = "bottom")

```
