---
title: "CEA anticoag"
author: "Emily O'Neill, Andrew Huang"
date: "2023-06-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r} 
##Cost utility analysis of Rivaroxaban in the prevention of VTE reoccurrence versus standard or care with warfarin: A markov Model-Based Simulation  

##remove any variables in R's Memory 
rm(list = ls()) 

##Install packages for Markov Model 
library("heemod")
library("diagram")
library("flexsurv")
library("mstate")
library("hesim")
library("BCEA")
library("ggplot2")
library("scales")
library("data.table")

# Load Markov model function for rivaroxaban and warfarin
source("function_markov.R")

``` 

Rivaroxaban - try a single simulation with point estimates

Model hyperparameters
```{r} 
##Model Input 
n.t   <- 12                                       # time horizon, 12 cycles 
d.c   <- d.e <- 0.05                              # Equal discounting of costs and QALYs by 5%

#The model states: 
#(1) No Event = NE; 
#(2) VTE Recurrence = VR; 
#(3) Major Bleed = MB; 
#(4) Clinically relevant Non-Major Bleed = NMB; 
#(5) Off Treatment = OT 

v.n   <- c("NE", "VR", "MB", "NMB", "OT")         # Model states  
v.M_1 <- c(1, 0, 0, 0, 0)                         # Everyone begins in index event

``` 

Model parameters for Rivaroxaban
```{r}
###Rivaroxaban### 

##Health States  
#Transition probabilities (per cycle): 
pr.ne_ne   <- 0.856               # probability from no event to no event  
pr.ne_vr   <- 0                   # probability from no event to VTE recurrence 
pr.ne_mb   <- 0.019               # probability from no event to  major bleed 
pr.ne_nmb  <- 0.125               # probability from no event to CRNMB
pr.nmb_ot  <- 0.019               # probability from CNMB to come off treatment  
pr.mb_ot   <- 1                   # probability from MB to come off treatment  

#List of parameter values for state transition probabilities
l.probr <- list(pr.ne_ne=pr.ne_ne,
                pr.ne_vr=pr.ne_vr,
                pr.ne_mb=pr.ne_mb,
                pr.ne_nmb=pr.ne_nmb,
                pr.nmb_ot=pr.nmb_ot,
                pr.mb_ot=pr.mb_ot)

##Cost
c.ne      <- 142                #Cost for staying healthy in rivaroxaban arm
c.vr      <- 215                #Cost for VTE recurrence in Rivaroxaban arm ($73) 
c.mb      <- 490                #Cost for major bleed in Rivaroxaban arm ($348)
c.nmb     <- 304                #Cost for CRNMB in Rivaroxaban arm ($162)
c.ot      <- 0                  #Cost of off treatment

##Utility Values 
u.ne    <- 0.825               #Utility of No Event
u.vr    <- 0.76                #Utility of recurrence  
u.mb    <- 0.65                #Utility of major bleed
u.nmb   <- 0.61                #Utility of CRNMB 
u.ot    <- 0.59                #Utility of off treatment 

##Vectors for cost and utility values 
v.cost <- c(c.ne, c.vr, c.mb, c.nmb, c.ot)
v.util <- c(u.ne, u.vr, u.mb, u.nmb, u.ot)

``` 

```{r}

##Run the Simulation  
sim_markov_riv <- Markov(n.t, d.c, d.e, v.n, v.cost, v.util, v.M_1, l.probr)

sim_markov_riv
```


```{r} 
###CEA 

##Store the mean costs of each medication 
v.c <- c(sim_markov_w$tc_hatw, sim_markov_r$tc_hatr) 
##store the mean QALY of each medication  
v.e <- c(sim_markov_w$te_hatw, sim_markov_r$te_hatr)


## ICER ##
delta.c <- v.c[2] - v.c[1]            # calculate incremental costs between rivaroxaban and warfarin 
delta.e <- v.e[2] - v.e[1]            # calculate incremental QALYs between rivaroxaban and warfarin
ICER <- delta.c / delta.e             # calculate the ICER
results <- c(delta.c, delta.e, ICER)  # store the values in a new variable

# Create full incremental cost-effectiveness analysis table
table_markov <- data.frame(
  round(v.c, 0),              # costs per arm
  round(v.e, 3),              # health outcomes per arm
  c("", round(delta.c, 0)),   # incremental costs
  c("", round(delta.e, 3)),   # incremental QALYs
  c("", round(ICER, 0))       # ICER
)
rownames(table_markov) = v.Trt  # name the rows
colnames(table_markov) = c("Costs", "QALYs","Incremental Costs", "QALYs Gained", "ICER") # name the columns
table_markov                    # print the table 
```

```{r} 
### CEA with Monte Carlo Simulation ###

#Estimate the STD from CI and Z-scores
std_dev_prob_R = (1.04 - 0.44) / (2 * 1.96)  

std_dev_prob_MB = (1.30 - 0.33) / (2 * 1.96) 

std_dev_prob_NMB = (1.22 - 0.76) / (2 * 1.96) 

#Number of MC Samples
n_samples <- 10  

#Set the random number seed for reproducibility
set.seed(123) 

#Warfarin
sample_pw_vr <- rnorm(n_samples, 0.021, std_dev_prob_R)
sample_pw_mb <- rnorm(n_samples, 0.008, std_dev_prob_MB)
sample_pw_nmb <- rnorm(n_samples, 0.081, std_dev_prob_NMB) 

#Rivaroxaban  
#this is 0.03 + 2*STD normalized to sum to a max of 1 
sample_pr.ne_vr <- runif(n_samples, min = 0, max = 0.289473684) 
#this is 0.012 + 2*STD normalized to sum to a max of 1
sample_pr.ne_mb  <- runif(n_samples, min = 0, max = 0.438596491) 
#this is 0.081 + 2*STD normalized to sum to a max of 1 
sample_pr.ne_nmb  <- runif(n_samples, min = 0, max = 0.271929825) 
sample_pr.ne_ne   <- 1 - sum(sample_pr.ne_vr, sample_pr.ne_mb, sample_pr.ne_nmb)  
sample_pr.nmb_ot  <- runif(n_samples, min = 0, max = .15) 
sample_pr.nmb_nmb <- 1 - sample_pr.nmb_ot 
sample_pr.mb_ot   <- runif(n_samples, min = .8, max = 1) 
sample_pr.mb_mb   <- 1 -sample_pr.mb_ot 

#Initialize empty vectors to store results
  v.c <- numeric()
  v.e <- numeric()

for (i in 1:n_samples) {
#Update the transition probabilities with the sampled values
    pr.ne_vr <- sample_pr.ne_vr[i]
    pr.ne_mb <- sample_pr.ne_mb[i]
    pr.ne_nmb <- sample_pr.ne_nmb[i]
    pr.ne_ne <- sample_pr.ne_ne[i]
    pr.nmb_ot <- sample_pr.nmb_ot[i]
    pr.nmb_nmb <- sample_pr.nmb_nmb[i]  
    pr.mb_ot   <- sample_pr.mb_ot [i] 
    pr.mb_mb   <- sample_pr.mb_mb [i] 
   
#Tranistion state probability matrix
#t.probr <- matrix(c(pr.ne_ne, pr.ne_vr, pr.ne_mb, pr.ne_nmb, 0, 
                 # 0, 1, 0, 0, 0, 
                  #0, 0, pr.mb_mb, 0, pr.mb_ot, 
                  #0, 0, 0, pr.nmb_nmb, pr.nmb_ot, 
                  #0, 0, 0, 0, 1), 
                #nrow = n.s, ncol = n.s, byrow = T, 
                #dimnames = list (v.n, v.n)) 

#Run the Markov model for each sample
#sim_markov_w <- Markov(v.M_1, n.t, v.n, d.c, d.e, Trt = FALSE)
sim_markov_r <- Markov(v.M_1, n.t, v.n, d.c, d.e, Trt = TRUE)
    
#Store the costs and outcomes for each sample
#v.c[i] <- sim_markov_r$tc_hatr - sim_markov_w$tc_hatw
#v.e[i] <- sim_markov_r$te_hatr - sim_markov_w$te_hatw 
v.c <- append(v.c,sim_markov_r$tc_hatr)
v.e <- append(v.e,sim_markov_r$te_hatr)
  }
  
print(list(v.c = v.c, v.e = v.e)) 

```